#!/bin/bash
set -e

ENV_FILE="$1"
CMD="${@:2}"

set -o allexport

# Source the file
source ".env.${ENV_FILE}"

# Dynamically set the commit version
# We only set if not running in github actions
if [[ -z "${GITHUB_SHA}" ]];
  # GITHUB_SHA is not set.
  then COMMIT_SHA=$(git rev-parse HEAD);
  else COMMIT_SHA=$GITHUB_SHA;
fi

set +o allexport

$CMD
